services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"

  api:
    build: .
    command: uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file: .env
    depends_on:
      - db
      - redis
      - chromadb

  worker:
    build: .
    command: celery -A core.orchestrator.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
      - api

volumes:
  postgres_data:
